### ISSUE TITLE
Missing ability to define Kubernetes Ingress settings

### ISSUE THREAD

**Issue by bezerker** [containous/traefik-helm-chart#140]
In the stable traefik chart, I require a section in my values like so

kubernetes:
  ingressEndpoint:
    useDefaultPublishedService: true

Without this I cannot properly see an externalIP on my traefik-ingress service.

This chart doesn't appear to set this. :(

**Comment by mmatur** [comment]
Hi @bezerker ,

Thanks for your question. 

In this chart there is no default value for the published service. But this is something that you can solved with the following `values.yaml`

```yaml
additionalArguments:
  - "--providers.kubernetesingress.ingressendpoint.publishedservice=default/traefik"
```

And by using the following installation command:

```bash
helm install traefik traefik/traefik --values values.yaml
```

Cf [documentation](https://docs.traefik.io/providers/kubernetes-ingress/#publishedservice)

I will close this issue because I think your question is answered .

**Comment by bezerker** [comment]
This does answer my question! Thanks so much and much appreciated.
