### ISSUE TITLE
Error configuring TLS: secret does not exist when trying to access a secret from another namespace

### ISSUE THREAD

**Issue by Mokto** [containous/traefik-helm-chart#61]
Hi,

So, when I'm trying to use a TLS configuration from another namespace, traefik can't access the secret.

NAMESPACE traefik:
- traefik
- cert-manager deployment

NAMESPACE other-namespace:
- service (any web service)
- certificate generated from cert-manager (named service-certs)
- ingressroute

When everything is in the same namespace, I don't have any issue.
When in separated namespaces, I get this : `Error configuring TLS: secret other-namespace/service-certs does not exist`

Everything seems right here though : https://github.com/containous/traefik-helm-chart/blob/master/templates/rbac/clusterrole.yaml. But my knowledge in RBAC is pretty limited.

Thanks !

**Comment by chiting** [comment]
From my understanding, secrets are restricted to their namespaces: https://kubernetes.io/docs/concepts/configuration/secret/#details

One of the options would be to create the same secret in all the namespaces you want to use it from.

**Comment by dduportal** [comment]
Hi @Mokto @chiting , you are right, secrets are restricted per namespace. It is not related to Traefik, but to Kubernetes behavior.

You might want to check this thread in the community forum where there is an example of storing TLS certificates as secrets in Traefik's namespace, and how to configure the IngressRoute in another namespace: https://community.containo.us/t/can-i-set-namespace-for-tls-secretname-in-ingressroute/2619/4. 

However, if the secret is in the same namespace as the IngressRoute, it should work.
@Mokto , do you mind switching to the community forum and providing a reproduction case so we can help you? The issue tracker here is related to specific elements on the Helm chart, and it looks like your issue is either a configuration issue, either something related to Traefik.

Hope it helps.
